# Generated by Django 6.0.3 on 2026-03-09 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_relatorio', models.IntegerField()),
                ('local', models.CharField(max_length=200)),
                ('auditor', models.CharField(max_length=200)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('C', 'Conforme'), ('NC', 'Não Conforme'), ('NA', 'Não Aplica')], max_length=2)),
                ('auditoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditoria.auditoria')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditoria.item')),
            ],
        ),
    ]
