# Generated by Django 6.0.3 on 2026-03-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='grupo',
            field=models.CharField(default='TEMP', max_length=200),
            preserve_default=False,
        ),
    ]
