# Generated by Django 6.0.3 on 2026-03-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0002_item_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='resposta',
            name='motivo_nc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resposta',
            name='tratativa',
            field=models.TextField(blank=True),
        ),
    ]
